### ISSUE TITLE
OpenVocabCodeNLM

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#98] opened 2020-01-31 00:04 UTC
https://github.com/researchart/rose6icse/tree/master/submissions/available/OpenVocabCodeNLM
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/OpenVocabCodeNLM

- Hlib Babii (corresponding)
  - email: hlibbabii@gmail.com
  - github id: [hlibbabii](https://github.com/hlibbabii)

- Rafael-Michael Karampatsis
  - email: mpatsis13@gmail.com
  - github id: [mpatsis](https://github.com/mpatsis)

## Note to reviewers: these authors want multiple badges
- reusable
- available

**Comment by anonymous-002** [comment] 2020-02-06 12:49
Thanks for submitting your artifacts. I tried to follow your instructions in the _install.md_ file, but I could not run the docker image you provided. I have never used Docker before, so I followed your instructions for OSX and they seemed to run correctly. At least, the Hello World image issued a message saying that Docker might be installed correctly.

```
latest: Pulling from library/hello-world
1b930d010525: Pull complete 
Digest: sha256:9572f7cdcee8591948c2963463447a53466950b3fc15a247fcad1917ca215a2f
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.
```

However,  when I tried to run your image, I took the following error:

```bash
$ docker run -it hlib/open-vocab-code-nlm
docker: Cannot connect to the Docker daemon at tcp://192.168.99.100:2376. Is the docker daemon running?.
See 'docker run --help'.

$ docker run -it hlib/open-vocab-code-nlm
docker: error during connect: Post https://192.168.99.100:2376/v1.40/containers/create: dial tcp 192.168.99.100:2376: connect: host is down.
See 'docker run --help'.
```

I searched Google for an answer and found this link (https://github.com/docker/toolbox/issues/453) that suggests removing the default machine and recreating it. Doing so, I was able to download and run your Docker image. Maybe you could add the commands to remove and recreate the default machine at the start of the "Running demonstration" section.

```bash
$ docker-machine rm default
$ docker-machine create default --driver virtualbox
$ docker-machine env default
$ eval "$(docker-machine env default)" 
```

Afterward, I could move on and run the demonstrations scripts. The `vocab_study.sh` script runs successfully but its outputs are very unclear and the only hints to what it is doing are the messages relating to sections of the paper, such as word splitting and BPE. Nevertheless, it runs.

The `nlm.sh` script is harder to understand. It starts issuing several `tensorflow` warnings, most related to deprecation. Then, it outputs the following message ...

```
Test perplexity is 3.3312940915651232

Total time 0:00:51.652945
Done testing!
```

... followed by the errors below.

```
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'Train/init' type=NoOp>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/src/app//OpenVocabCodeNLM/code_nlm.py", line 2275, in main
    print("Done training!")  File "/usr/src/app//OpenVocabCodeNLM/code_nlm.py", line 2058, in do_test
    print("\n\nTest perplexity is " + str(test_perplexity) + "\n")  File "/usr/src/app//OpenVocabCodeNLM/code_nlm.py", line 2076, in create_model
    return model  File "/usr/src/app//OpenVocabCodeNLM/code_nlm.py", line 195, in __init__
    self.summary = tf.summary.merge_all()  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
E0206 13:26:50.252042 140203071366976 tf_should_use.py:76] ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'Train/init' type=NoOp>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/src/app//OpenVocabCodeNLM/code_nlm.py", line 2275, in main
    print("Done training!")  File "/usr/src/app//OpenVocabCodeNLM/code_nlm.py", line 2058, in do_test
    print("\n\nTest perplexity is " + str(test_perplexity) + "\n")  File "/usr/src/app//OpenVocabCodeNLM/code_nlm.py", line 2076, in create_model
    return model  File "/usr/src/app//OpenVocabCodeNLM/code_nlm.py", line 195, in __init__
    self.summary = tf.summary.merge_all()  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
```

In the end, I am not certain whether the script worked or not. As these scripts are presented as demonstrations, would there be any way to make their outputs clearer?

**Comment by hlibbabii** [comment] 2020-02-06 16:56
@anonymous-002  Thanks a lot for pointing out the problem with docker installation and spending time on making it work (hopefully it did not take you too much effort)! We will add the lines you suggested to the instructions.

Regarding the `nlm.sh` script,  it indeed finished successfully. The `tensorflow` warnings and the last error in particular (which is also more like a warning than an error) are due to a higher `tensorflow` version used in the docker container. We are very sorry for this and will fix it in addition to adding more information about what is happening during the execution in both scripts.

We will submit a new pull request with the fixes as soon as possible.

**Comment by anonymous-002** [comment] 2020-02-06 20:21
Thanks, @hlibbabii. Please, let me know when the pull request is done. I am already ok with the artifacts you made available, but a clearer output would be great.

**Comment by hlibbabii** [comment] 2020-02-09 16:48
@anonymous-002 , I have submitted the pull request.

**Comment by anonymous-002** [comment] 2020-02-10 18:29
Thanks, @hlibbabii.

**Comment by gorocketsgo** [comment] 2020-02-14 03:02
The authors apply for both the AVAILABLE and REUSABLE badges. There are three artifacts, including a library for code preprocessing, the implementation of the NML models with training and testing scripts, and a set of pre-trained models in different configurations. The artifacts are well prepared with clear documentation. All artifacts have been uploaded to Zenodo with DOIs provided. Furthermore, the Java, Python, C code corpora used in the study are shared on DataShare with DOIs provided. 

I downloaded the Docker image and run the two scripts following the instructions. I didn't run into any issues. The outputs are all clear and very well-formatted. Though the `vocab_study.sh` script only runs on a subset of projects, the results look consistent with the findings in the paper, except two things. First, the `vocab.sh` script outputs "3.1 Split by conventions + numbers + RONIN" and "3.2 Split by conventions + numbers + romin + STEMMING", do "RONIN" and "romin" refer to the same thing? According to the paper, you used the Spiral token splitter. Why is it romin here? Second, the OOV rate for BPE is 13.94%, while the OOV rate for no-filtering is 0.23%. This looks like the opposite of your findings in the paper. Shouldn't BPE decrease the OOV rate? Regarding the `core_nlm.py` script, why does it always print the word perplexity instead of cross entropy even when the cross-entropy flag is set to true? I wish the authors could clarify these questions in the rebuttal. 

I didn't reproduce the result on the full dataset since it takes a long time. Instead, I run the commands in other testing scenarios in the Docker image. The outputs look correct.

Table 2 in the paper also shows results on different n-gram models. I cannot find those n-gram models in your artifacts. If you use the original implementation from Hellendoorn and Devanbu [41], can you provide a link to their GitHub repo and clarify in your README file?

Overall, the authors have done a very good job. I think we should give them the AVAILABLE and REUSABLE badges.

**Comment by timm** [comment] 2020-02-17 01:52
@anonymous-002 : please clarify your current view on reusable and available. thank you!

**Comment by anonymous-002** [comment] 2020-02-17 17:40
@timm sorry for the lack of clarity. I think the authors apply for both the AVAILABLE and REUSABLE badges.

**Comment by timm** [comment] 2020-02-20 17:53
currently, if no more more input, this will be available and reusable

@anonymous-002:but do you think they have reached AVAILABLE and REUSABLE badges?

**Comment by anonymous-002** [comment] 2020-02-20 19:12
Yes, indeed.

**Comment by hlibbabii** [comment] 2020-02-21 10:10
@timm, I am sorry If you expected an earlier reply from us. We were not sure if we should reply before the tag 'AuthorComment' is assigned to us.

@anonymous-002, @gorocketsgo, Thank you for your reviews and for another round of pointers to the typos and things to be clarified. The clarifications are provided below.

**Typos**. *Ro**m**in* is an accidentally misspelled word *Ro**n**in* with which we refer to the Ronin splitter implemented in the *Spiral* library (https://github.com/casics/spiral). So all these names refer to the same algorithm.
Printing *"Test perplexity is"* in the `core_nlm.py` script instead of *"Test cross-entropy is"* is another unfortunate typo. When the cross-entropy flag is specified, the value which is calculated and printed is the cross-entropy as it should be. Only the text description is incorrect. 
We apologize if these issues caused confusion.

**OOV rate**. When refactoring the script to better visualize the results for the artifact presentation, we indeed introduced a bug, which we, to our own surprise, overlooked. Definitely, the trend of the decreasing OOV rate should be observed even for a tiny dataset. We have made a fix and now you will see the OOV values as you would expect them:
![image](https://user-images.githubusercontent.com/2955794/75012064-7b0a2c00-5481-11ea-8721-023749b2354c.png)

Note, this is a bug on the presentation level and it did not affect the correctness of the `codeprep` library output and our study results reported in the paper.

**N-gram models**. It is true that for the evaluation of n-gram modes we used the original implementation from Hellendoorn and Devanbu [41]: https://github.com/SLP-team/SLP-Core. We used v0.1 of their models, which is the version used in their reported experiments. We added this information to the README of the artifact repository.

**Comment by timm** [comment] 2020-02-21 16:40
@anonymous-002 thank you for a clear statement of your conclusions

so now we have a new merged pull request (thanks to @hlibbabii: much appreciated)

@gorocketsgo : currently we are "reusable" and "available". so please advise: what is your call on these badges? veto or confirm?

**Comment by gorocketsgo** [comment] 2020-02-21 21:22
@timm I confirm the decision that both badges should be granted.

**Closed as completed** 2020-02-22 05:54 UTC
Labels: Available, Reusable
