### ISSUE TITLE
DeepInspect

### ISSUE THREAD

**Issue by timm** [researchart/rose6icse#27] opened 2020-01-26 14:03 UTC
https://github.com/researchart/rose6icse/tree/master/submissions/available/icse20-main-536
https://github.com/researchart/rose6icse/tree/master/submissions/reusable/icse20-main-536

- Yuchi Tian
  - email: yt2667@columbia.edu
  - github ids: [yuchi1989](https://github.com/yuchi1989)

- Ziyuan Zhong
  - email: zz2521@columbia.edu
  - github ids: [AIasd](https://github.com/AIasd)

## Apply for the Reusable and Available Badges

**Comment by blind-reviewer-2** [comment] 2020-02-10 11:53
Hi authors,

I have run into quite a few errors while trying to get the final part of your code functioning. I pulled the pytorch docker container to run your code inside of, and I am now running into this error:

```shell
root@3561e1cea4ff:/workspace/DeepInspect/deepinspect/robust_cifar10# python2 cifar10_small_deepinspect.py
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar-10-python.tar.gz
100%|#########9| 170352640/170498071 [01:18<00:00, 2057343.56it/s]Extracting ./data/cifar-10-python.tar.gz to ./data
Traceback (most recent call last):
  File "cifar10_small_deepinspect.py", line 591, in <module>
    get_yhats_test()
  File "cifar10_small_deepinspect.py", line 46, in get_yhats_test
    model = select_model('small')
  File "cifar10_small_deepinspect.py", line 41, in select_model
    model = pblm.cifar_model().cuda() 
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 101, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
170500096it [01:21, 2091108.71it/s] 
```
Is there a config option you can set or recommend so that people without a GPU can run your code?

**Comment by yuchi1989** [comment] 2020-02-10 20:36
Hi, sorry for the inconvenient.  The code requires at least one GPU with CUDA installed and pytorch with cuda enabled in the environment to run.

**Comment by blind-reviewer-2** [comment] 2020-02-11 18:04
Hi Authors,

I was able to run the first two steps, thereby generating the figures. However, I was unable to replicate the deepinspect testing of the models because I do not have access to a system with GPU. While I feel this is perhaps unfair to you, since you cannot control my environment, I also think you should consider what this means for future use of your artefacts. I have replicated the work of other artefacts with the same Python libraries as your project has, using their config file that allowed me to select "no GPU available". The lack of such a configuration option greatly decreases the usability and reach of your artefacts. With these comments in mind, I am unable to recommend the badge "Reusable".

The data is only available on Github, which is not a "publicly accessible archival repository." Please use a service such as Zenodo, FigShare, or Software Heritage. This is a requirement in order to obtain the badge of "Available." However, also required to receive that badge includes the requirements of the "Functional" badge, which I am not able to verify. With this in mind, I cannot recommend the badge of "Available" at this time.

### Given the current state of the repository, I cannot recommend any badge.

##### Reusable Badge (+ Functional)

Installation and Running Comments

- Reproducing results in Table 3 and Figure 6 in paper
  - I was able to run the script with minimal effort and generate the terminal output and PDF.
- Reproducing results in Table 4 and Figure 10 in paper
  - For scripts that don't finish immediately (or have no progress bar), it is recommended that you state in the readme how long the script may take. Otherwise the user may think it has frozen or something similar. Another reason is that the user should know how long to dedicate to running your scripts. If the script takes many hours, they need to prepare a time when they can run the scripts without closing their computer.
  - Both were executed and ran fine. First one took 30 minutes and the second one took 5 minutes
- Apply deepinspect to testing robust CIFAR-10 models
  - Why not name the pip libraries as they need to be entered into the command line? E.g. `numpy==1.16` instead of `numpy-1.16`
  - Manually install pip libraries is nicely avoided by having requirements.txt files
    - Or, include these line in your readme:
      - `pip2 install numpy==1.16 tqdm==4.41 torch==1.3.1 torchsummary torchvision` 
      - `pip3 install numpy scipy matplotlib sklearn pandas`
  - Encountered error: `ImportError: No module named torchvision.models`. I had to `pip2 install torchvision` to fix it. Add this to your install.md
  - My pip2 installs were killed due to lack of resources, even with 8GM of RAM allocated. I had to increase to 14GB of RAM to fix. Please state some minimum system requirements since it is more than a standard install.

##### Available Badge

Dataset Availability: The data is only available on Github, which is not a "publicly accessible archival repository." Please use a service such as Zenodo, FigShare, or Software Heritage.
License: MIT

**Comment by DeepLearningInspect** [comment] 2020-02-11 23:02
Hi @blind-reviewer-2 , 
Thank you for your comments! we have added support of the CPU-only environment for replicating the deepinspect testing of the models by updating our code repository (you can pull [our repository](https://github.com/ARiSE-Lab/DeepInspect) to see the update and rerun the code). Besides, we have put our code and data on [![Zenodo](https://zenodo.org/badge/227184732.svg)](https://zenodo.org/badge/latestdoi/227184732) as suggested. We will also update our readme file as suggested.

**Comment by AIasd** [comment] 2020-02-11 23:05
Hi @blind-reviewer-2 ,
Thank you for your comments! we have added support of the CPU-only environment for replicating the deepinspect testing of the models by updating our code repository (you can pull [our repository](https://github.com/ARiSE-Lab/DeepInspect) to see the update and rerun the code without any additional changes). Besides, we have put our code and data on [![DOI](https://zenodo.org/badge/227184732.svg)](https://zenodo.org/badge/latestdoi/227184732) as suggested. We will also update our readme file as suggested.

**Comment by blind-reviewer-2** [comment] 2020-02-15 05:27
## Updated Review

Hi Authors,

Thank you for the update to your code. I was able to run the final step and produce results. My output matches the numbers in Table 3. Note: perhaps you can recommend which table to refer to when checking step 3 of "Expected outputs" (I originally found Table 4 and thought the numbers were wrong). With the current state of this repository, I can now recommend the badge of "Reusable".

Thank you for uploading your code to Zenodo. This greatly extends the use of your artefacts and helps ensure future use of your work. With the current state of this repository, I can now recommend the badge of "Available".

### Given the current state of the repository, I recommend the badges "Reusable" and "Available".

**Comment by timm** [comment] 2020-02-17 01:51
@github-anonymous : I look forward to your review.

**Comment by github-anonymous** [comment] 2020-02-17 16:47
### General remarks:

- Some experiments took a very long time and for a moment I thought that the artifact was not working (e.g., stuck on an infinite loop or something).

### Reusable badge + functional (reject):

- Reproduced experiments:
  * Reproducing results in Table 3 and Figure 6 in paper: OK
  * Reproducing results in Table 4 and Figure 10 in paper: OK
  * Apply deepinspect to testing robust CIFAR-10 models: not OK. I get an error (see image below) when trying to execute the artifact as described. 

![Cifar-10](https://user-images.githubusercontent.com/57346494/74672458-9dfcbd80-51ad-11ea-8a7d-ae472d41d117.jpg)

 
### Available Badge (accept):

- The authors comply with all requirements 
- Please update the *.md files with the DOI

**Comment by yuchi1989** [comment] 2020-02-17 16:54
@github-anonymous Thank you for your comments. I see you use python3 to run cifar10_small_deepinspect.py. Could you please use python2 to run it as described in INSTALL.md? If you use python2 to run cifar10_small_deepinspect.py, it will work. Thank you! 
I also attached part of the related running commands in both README.md and INSTALL.md below.
#### Prerequisite
```
OS: Ubuntu 18.10  
Python 2.7 with library numpy-1.16, tqdm-4.41, torch-1.3.1, torchsummary, torchvision  
Python 3.7/3.8 with library numpy, scipy, matplotlib, sklearn, pandas
```
#### Run deepinspect on robust training CIFAR-10 models to generate csv files
```
cd ${ROOTFOLDER}/deepinspect/robust_cifar10/
rm *.csv
rm *.pickle
python2 cifar10_small_deepinspect.py
```

**Comment by github-anonymous** [comment] 2020-02-19 15:10
> @github-anonymous Thank you for your comments. I see you use python3 to run cifar10_small_deepinspect.py. Could you please use python2 to run it as described in INSTALL.md? If you use python2 to run cifar10_small_deepinspect.py, it will work. Thank you!
> I also attached part of the related running commands in both README.md and INSTALL.md below.
> 
> #### Prerequisite
> ```
> OS: Ubuntu 18.10  
> Python 2.7 with library numpy-1.16, tqdm-4.41, torch-1.3.1, torchsummary, torchvision  
> Python 3.7/3.8 with library numpy, scipy, matplotlib, sklearn, pandas
> ```
> 
> #### Run deepinspect on robust training CIFAR-10 models to generate csv files
> ```
> cd ${ROOTFOLDER}/deepinspect/robust_cifar10/
> rm *.csv
> rm *.pickle
> python2 cifar10_small_deepinspect.py
> ```

Dear authors,
I followed your instructions and now I have the following issue:
![Cifar-10](https://user-images.githubusercontent.com/57346494/74847363-49367f80-5332-11ea-8be3-002e7b2b7aa5.jpg)
![Cifar-10-2](https://user-images.githubusercontent.com/57346494/74847366-4b004300-5332-11ea-8631-e78c6cb86426.jpg)

**Comment by yuchi1989** [comment] 2020-02-19 15:59
@github-anonymous Thank you for your comments. You can see that the error comes from "import torchvision.models" This is an environment issue because of a pytorch bugs, see the following two links. A fix is to change to another pytorch and torchvision version. Here is a recommended version. 
`pip2 install numpy==1.16 tqdm==4.41 torch==1.3.1 torchsummary torchvision==0.4.2` 
Don't forget to remove all .pickle and .csv file in  ${ROOTFOLDER}/deepinspect/robust_cifar10/ folder before run cifar10_small_deepinspect.py Thank you very much!
 
https://github.com/pytorch/vision/issues/1675
https://www.gitmemory.com/issue/pytorch/vision/1675/566573754

**Comment by github-anonymous** [comment] 2020-02-19 19:28
### Updated Review

Dear Authors,

Thanks for the explanations.
I assert that the artifacts work, please update the *.md files with the required information.
I recommend the badges "Reusable" and "Available".

**Comment by yuchi1989** [comment] 2020-02-19 20:15
Thank you very much for both reviewers' comments. I have just created a pull request adding DOI information and update the md files based on your comments. Currently it is waiting to be merged.

**Comment by yuchi1989** [comment] 2020-02-20 01:37
Hi reviewers, I see that the pull request updating *.md files has been merged. Please let me know if you have more comments or questions. Thank you!

**Closed as completed** 2020-02-20 18:36 UTC
Labels: Available, Reusable
