### ISSUE TITLE
neural_code_generation_and_summarization_replications

### ISSUE THREAD

**Issue by minkull** [researchart/rose6icse#158] opened 2020-02-04 22:42 UTC
https://github.com/researchart/rose6icse/tree/master/submissions/replicated/neural_code_generation_and_summarization_replications

# Authors of replication / reproduction
- Nicolas Chausseau, nico3865
- Peter Rigby

**Comment by minkull** [comment] 2020-02-04 22:42
@nico3865 You have 2 replications and 1 reproduction. Please could you clarify if they are all part of the same study? If not, could you create separate submissions for each of them?

**Comment by nico3865** [comment] 2020-02-04 23:20
Hi Leandro,

Yes in theory the two replications and the reproduced baseline are all part
of the same study, because the goal was to compare several models on the
same dataset (CoNaLa), for a fair comparison.

Is it possible to combine them in one publication? That would be ideal.
Otherwise I can create 3 separate submissions, but in that case I wouldn't
know where to put the discussion about the comparisons.

Thanks,

Nicolas

**Comment by minkull** [comment] 2020-02-05 08:26
@nico3865 That's ok if they are all part of the same study. No need to create the separate submissions.

**Comment by nico3865** [comment] 2020-02-05 16:53
Ok great! Thank you,
Nicolas

**Comment by icse2020review** [comment] 2020-02-16 04:52
The authors provide the replication packages for all artifacts explored in this study along with the dataset used in the conducted experiments. They also made the results obtained publicly available on dropbox folders. 

I am wondering if the authors can provide more detailed instructions on the replication steps. Also, it would be great if the authors can provide a ready to use VM image.

**Comment by timm** [comment] 2020-02-16 22:31
@icse-2020-reviewer : have u finished your review? are you saying that right now you cannot decide available or reproducible?

**Comment by icse-2020-reviewer** [comment] 2020-02-17 00:15
@timm I (icse-2020-reviewer) don't think that I'm assigned to this paper as a reviewer.

**Comment by timm** [comment] 2020-02-17 00:39
apologies to@icse-2020-reviewer . I should have pinged @icse2020review

@icse2020review: have u finished your review? are you saying that right now you cannot decide available or reproducible?

**Comment by nico3865** [comment] 2020-02-18 19:05
Hi Tim and @icse2020review <https://github.com/icse2020review>,

I could provide VMs, yes.
The model's code and the datasets (CoNaLa, java-docstring) are already
available (see links), with detailed instructions from the original papers
on how to use them, so I thought it wasn't necessary to submit a new Github
or VM.

But yes I could provide a VM that contains both the models and datasets,
everything installed and ready to run.

Should I make those VMs available for download, from a url? They will be
too big for a Github repo.

Also, please le me know by what date the link(s) should be available.

Thank you!

Nicolas

**Comment by timm** [comment] 2020-02-19 05:43
so we are currently at "reproduced" and awaiting configuration or veto on that from  @helpacksi

**Comment by helpacksi** [comment] 2020-02-19 11:36
##### Notes on results and original studies--
The authors have made available the following artifacts in this study
- [X] The results obtained in the form of a drop box link.
- [X] Links to the original replication packages and the data set source for the two comparative studies

##### Notes on authors' reproduction of the original study--
- [ ] The linked repository for reproduction does not have a README and/or further instruction to run the code and "reproduce" the results. 

##### So currently I would categorize this as: *Available*

**Comment by nico3865** [comment] 2020-02-19 20:17
Ok yes, absolutely, I do need to provide a README for the baseline
reproduction (and also clean the code).

So please let me know if everything else seems in order, and I would:

   - provide a README for the reproduction (and clean the repository)
   - provide a VM that contains pre-installed datasets + models ready to
   run.


Thanks,

Nicolas

**Comment by minkull** [comment] 2020-02-20 18:54
@nico3865 we will need modifications asap to reach a decision.

@helpacksi Please could you let @nico3865 know if those modifications are enough to award reproduced?

**Comment by timm** [comment] 2020-02-22 13:03
so we are currently at "reproduced" and awaiting configuration or veto on that from @helpacksi

**Comment by helpacksi** [comment] 2020-02-22 13:33
@nico3865 Thanks for your response. Those changes will be adequate.

**Closed as completed** 2020-02-22 17:10 UTC
Labels: Available, Reproduced
